# tasks file
---
- name: install
  apt:
    name: "{{ integrit_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - integrit
    - integrit-install

- name: update configuration file - /etc/integrit/integrit.debian.conf
  template:
    src: etc/integrit/integrit.debian.conf.j2
    dest: /etc/integrit/integrit.debian.conf
    owner: root
    group: root
    mode: 0600
  tags:
    - configuration
    - integrit
    - integrit-configuration

- name: update configuration file - /etc/integrit/integrit.conf
  template:
    src: etc/integrit/integrit.conf.j2
    dest: /etc/integrit/integrit.conf
    owner: root
    group: root
    mode: 0600
  notify: remove known db (once)
  tags:
    - configuration
    - integrit
    - integrit-configuration
